on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          path: src/github.com/Seeweb/cloudserver-go-client/
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      -
        name: Run tests
        run: |
          export GOPATH=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/src/github.com/Seeweb/cloudserver-go-client/
          make vet
          make test
